### ISSUE TITLE
Sony Alpha 7s continuous shooting with shutter speed longer than 30s?

### ISSUE THREAD

**Issue by ArminPro** [gphoto/gphoto2#120] opened 2018-02-27 14:23 UTC
Hi,
I´ve read so many issues but cannot read all. (-:
I am doing astrofotography and therefore would like to do tethering my Sony Alpha 7s via USB with gPhoto2.
What I especially would like to do is: Continuous or serial capturing in Modus M  with BULB, for example capture 20 times with shutter speed of 180 seconds with wait time 4 seconds in between.
Must I still wait 180s for download when my shutter speed is 180s?
These are the commands I found, some caused problems, but I do not know if they are solved.

gphoto2 --set-config bulb=1 --wait-event=180s --set-config bulb=0 --wait-event-and-download=180s
gphoto2 -F 20 -I 4 --capture-image-and-download
gphoto2 --capture-image-and-download -- interval 4 -- frames 20

What would be the common command?

Thanks and regards,
Armin

**Comment by msmeissn** [comment] 2018-04-02 15:57
one thing i saw is that the sony calculates a dark image with the same exposure length. 

Your first line will do bulb capture once.

Your last lines will have identical results as -I is --interval and -F is --frames, but both will not cause bulb capture..

If this could be switched off you could get this turnaround times by trying:

gphoto2 --bulb=180 -F 20 -I 4 --capture-image-and-download

The problem is the dark image which will cause this 180 seconds additional delay. Perhaps it can be switched off in a camera menu?

**Comment by ArminPro** [comment] 2018-04-19 06:50
I don´t let calculate the dark image.
But in the meanwhile I´ve solved the problem using a bash script:

#!/usr/bin/env bash

#Variables:
# $1 Number of Frames
# $2 Exposure Time in s
# $3 ISO Value

echo "#Capturing Frames = $1 with Exposure Time = $2s"
gphoto2 --set-config iso=$3

for ((i=1; i<=$1; i++))
do 
  gphoto2 \
  --filename "20%y_%m_%d-%H_%M_%S_$i.ARW"   \ 
  --set-config bulb=1                       \
  --wait-event=$2s                          \
  --set-config bulb=0                       \
  --capture-image-and-download
done

**Comment by dabu81** [comment] 2019-10-17 05:33
Thank you for your script. 
It helped me so much to get my Sony Alpha a58 running. I only had a problem that with your script after the main picture there was taken another picture with short exposure time. 
So I had to remove the last command and exchange it by --wait-event-and-download=2s

Here comes my version of the script:


#!/usr/bin/env

#bash Variables:

#$1 Number of Frames
#$2 Exposure Time in s
#$3 ISO Value

echo "#Capturing Frames = $1 with Exposure Time = $2s"
gphoto2 --set-config iso=$3

for ((i=1; i<=$1; i++))
 do gphoto2 --filename "20%y_%m_%d-%H_%M_%S_$i.ARW" --set-config bulb=1 --wait-event=$2s  --set-config bulb=0 --wait-event-and-download=2s
done

**Comment by msmeissn** [comment] 2019-10-20 19:01
I think this was resolved in some form

**Closed** 2019-10-20 19:01 UTC
Labels: Sony
